import{get,onValue,ref,remove,serverTimestamp,update}from'firebase/database';
import{realtimeDb}from'./client';
import type{RealtimePost,SupportTicket,UserProfile}from'./realtime';
export type AdminSupportTicket=SupportTicket&{uid:string};
export type AdminReport={id:string;reporterId:string;targetUid:string;postId?:string;type:'post'|'account';reason:string;status:'open'|'reviewed'|'resolved';createdAt:number;updatedAt?:number};
export type AdminConversation={id:string;initiatorId?:string;recipientId?:string;members:Record<string,boolean>;memberProfiles?:Record<string,{displayName:string;username:string}>;lastMessage?:string;lastMessageAt?:number;lastSenderId?:string};
export type AdminChatMessage={id:string;senderId:string;text:string;createdAt:number;mediaUrl?:string;replyTo?:string|null;editedAt?:number;seen?:boolean};
const needDb=()=>{if(!realtimeDb)throw new Error('VAYROX live data is not configured');return realtimeDb};
const rows=<T>(value:unknown)=>Object.entries((value||{}) as Record<string,unknown>).map(([id,v])=>({id,...(v as object)}) as T);
export function subscribeAllSupportTickets(cb:(items:AdminSupportTicket[])=>void){return onValue(ref(needDb(),'supportTickets'),snap=>{const data:AdminSupportTicket[]=[];Object.entries(snap.val()||{}).forEach(([uid,tickets])=>Object.entries((tickets as Record<string,unknown>)||{}).forEach(([id,value])=>data.push({uid,id,...value as Omit<SupportTicket,'id'>} as AdminSupportTicket)));data.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));cb(data)})}
export async function adminUpdateSupportTicket(uid:string,ticketId:string,status:SupportTicket['status']){await update(ref(needDb(),`supportTickets/${uid}/${ticketId}`),{status,updatedAt:serverTimestamp()})}
export function subscribeReports(cb:(items:AdminReport[])=>void){return onValue(ref(needDb(),'reports'),snap=>{const data=rows<AdminReport>(snap.val()).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));cb(data)})}
export async function adminUpdateReport(id:string,status:'reviewed'|'resolved'){await update(ref(needDb(),`reports/${id}`),{status,updatedAt:serverTimestamp()})}
export function subscribeAdminConversations(cb:(items:AdminConversation[])=>void){return onValue(ref(needDb(),'conversations'),snap=>cb(rows<AdminConversation>(snap.val()).sort((a,b)=>(b.lastMessageAt||0)-(a.lastMessageAt||0))))}
export function subscribeAdminMessages(conversationId:string,cb:(items:AdminChatMessage[])=>void){return onValue(ref(needDb(),`messages/${conversationId}`),snap=>cb(rows<AdminChatMessage>(snap.val()).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0))))}
export async function adminDeleteMessage(conversationId:string,messageId:string){const db=needDb();await remove(ref(db,`messages/${conversationId}/${messageId}`));await remove(ref(db,`messageReactions/${conversationId}/${messageId}`))}
export function subscribeAdminPosts(userIds:string[],cb:(items:RealtimePost[])=>void){const db=needDb();let publicPosts:RealtimePost[]=[],privatePosts=new Map<string,RealtimePost[]>();const emit=()=>cb([...publicPosts,...[...privatePosts.values()].flat()].sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)));const unsubs=[onValue(ref(db,'posts'),s=>{publicPosts=rows<RealtimePost>(s.val()).map(p=>({...p,isPrivate:false}));emit()})];for(const uid of [...new Set(userIds)])unsubs.push(onValue(ref(db,`privatePosts/${uid}`),s=>{privatePosts.set(uid,rows<RealtimePost>(s.val()).map(p=>({...p,isPrivate:true,privacyOwnerId:uid})));emit()},()=>{privatePosts.delete(uid);emit()}));return()=>unsubs.forEach(fn=>fn())}
export async function adminUserSnapshot(uid:string){const db=needDb(),paths=['users','following','followers','blocks','mutes','safetySettings','profilePrefs','notificationPrefs','accessibilityPrefs','onboarding','planIntent','deviceSnapshots'];const result:Record<string,unknown>={};for(const path of paths){const snap=await get(ref(db,`${path}/${uid}`));if(snap.exists())result[path]=snap.val()}return result}
export function labelConversation(c:AdminConversation,people:Map<string,UserProfile>){const ids=Object.keys(c.members||{});return ids.map(id=>people.get(id)?.username?`@${people.get(id)!.username}`:id).join(' ↔ ')||c.id}
