import{get,onDisconnect,onValue,push,ref,remove,serverTimestamp,set,update}from'firebase/database';
import{realtimeDb}from'./client';
import type{ChatMessage}from'./realtime';
export type RichChatMessage=ChatMessage&{mediaUrl?:string;replyTo?:string|null;editedAt?:number};
export type ConversationPreference={muted?:boolean;archived?:boolean};
export type MessageReactionMap=Record<string,Record<string,Record<string,boolean>>>;
const needDb=()=>{if(!realtimeDb)throw new Error('VAYROX live data is not configured');return realtimeDb};
export async function sendChatMessage(conversationId:string,uid:string,text:string,options?:{mediaUrl?:string;replyTo?:string|null}){const value=text.trim().slice(0,2000);if(!value&&!options?.mediaUrl)throw new Error('Message cannot be empty');const db=needDb(),node=push(ref(db,`messages/${conversationId}`)),preview=value||'Sent an image';await set(node,{senderId:uid,text:value,mediaUrl:options?.mediaUrl||null,replyTo:options?.replyTo||null,createdAt:serverTimestamp(),seen:false});await update(ref(db,`conversations/${conversationId}`),{lastMessage:preview,lastMessageAt:serverTimestamp(),lastSenderId:uid});return node.key}
export async function editChatMessage(conversationId:string,messageId:string,uid:string,text:string){const node=ref(needDb(),`messages/${conversationId}/${messageId}`),snap=await get(node);if(!snap.exists()||snap.child('senderId').val()!==uid)throw new Error('You can only edit your own message.');const value=text.trim().slice(0,2000);if(!value&& !snap.child('mediaUrl').exists())throw new Error('Message cannot be empty');await update(node,{text:value,editedAt:serverTimestamp()});await update(ref(needDb(),`conversations/${conversationId}`),{lastMessage:value||'Sent an image',lastMessageAt:serverTimestamp(),lastSenderId:uid})}
export async function deleteChatMessage(conversationId:string,messageId:string,uid:string){const node=ref(needDb(),`messages/${conversationId}/${messageId}`),snap=await get(node);if(!snap.exists()||snap.child('senderId').val()!==uid)throw new Error('You can only delete your own message.');await remove(node);await remove(ref(needDb(),`messageReactions/${conversationId}/${messageId}`))}
export async function toggleMessageReaction(conversationId:string,messageId:string,uid:string,emoji:'like'|'heart'|'laugh'){const node=ref(needDb(),`messageReactions/${conversationId}/${messageId}/${emoji}/${uid}`),snap=await get(node);await set(node,snap.exists()?null:true)}
export function subscribeMessageReactions(conversationId:string,cb:(value:MessageReactionMap)=>void){return onValue(ref(needDb(),`messageReactions/${conversationId}`),s=>cb((s.val()||{}) as MessageReactionMap))}
export async function markConversationRead(uid:string,conversationId:string){await set(ref(needDb(),`conversationReadsByUser/${uid}/${conversationId}`),serverTimestamp())}
export function subscribeReadStates(uid:string,cb:(values:Record<string,number>)=>void){return onValue(ref(needDb(),`conversationReadsByUser/${uid}`),s=>cb((s.val()||{}) as Record<string,number>))}
export function subscribeConversationRead(uid:string,conversationId:string,cb:(value:number)=>void){return onValue(ref(needDb(),`conversationReadsByUser/${uid}/${conversationId}`),s=>cb(Number(s.val())||0))}
export async function setConversationTyping(conversationId:string,uid:string,active:boolean){const node=ref(needDb(),`typing/${conversationId}/${uid}`);if(active){await onDisconnect(node).remove();await set(node,serverTimestamp())}else await set(node,null)}
export function subscribeConversationTyping(conversationId:string,uid:string,cb:(typing:boolean)=>void){return onValue(ref(needDb(),`typing/${conversationId}`),s=>{const value=(s.val()||{}) as Record<string,number>;cb(Object.entries(value).some(([id,time])=>id!==uid&&Date.now()-Number(time)<8000))})}
export function messageSeenBy(readAt:number,message:ChatMessage){return Boolean(readAt&&message.createdAt&&readAt>=message.createdAt)}
export async function setConversationPreference(uid:string,conversationId:string,key:keyof ConversationPreference,value:boolean){await set(ref(needDb(),`conversationPrefs/${uid}/${conversationId}/${key}`),value||null)}
export function subscribeConversationPreferences(uid:string,cb:(value:Record<string,ConversationPreference>)=>void){return onValue(ref(needDb(),`conversationPrefs/${uid}`),s=>cb((s.val()||{}) as Record<string,ConversationPreference>))}
