import { getApp,getApps,initializeApp } from 'firebase/app';
import { getAuth,GoogleAuthProvider } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';
import { getDatabase } from 'firebase/database';
const config={apiKey:process.env.NEXT_PUBLIC_FIREBASE_API_KEY,authDomain:process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,projectId:process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,storageBucket:process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,appId:process.env.NEXT_PUBLIC_FIREBASE_APP_ID,databaseURL:process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL};
export const firebaseConfigured=Boolean(config.apiKey&&config.projectId);
export const firebaseApp=firebaseConfigured?(getApps().length?getApp():initializeApp(config)):null;
export const auth=firebaseApp?getAuth(firebaseApp):null;
export const db=firebaseApp?getFirestore(firebaseApp):null;
export const realtimeDb=firebaseApp?getDatabase(firebaseApp):null;
export const googleProvider=new GoogleAuthProvider();
