import{get,onValue,push,query,ref,remove,set,update,orderByChild,limitToLast}from'firebase/database';import{realtimeDb}from'./client';import type{GroupConversation,GroupMessage}from'./product';
const db=()=>{if(!realtimeDb)throw new Error('VAYROX live data is not configured');return realtimeDb};
export function subscribeGroup(id:string,cb:(v:GroupConversation|null)=>void){return onValue(ref(db(),`groupConversations/${id}`),s=>cb(s.exists()?{id,...s.val()}:null))}
export function subscribeGroupRoomMessages(id:string,cb:(items:GroupMessage[])=>void){const q=query(ref(db(),`groupMessages/${id}`),orderByChild('createdAt'),limitToLast(200));return onValue(q,s=>cb(Object.entries(s.val()||{}).map(([mid,v])=>({id:mid,...(v as Omit<GroupMessage,'id'>)}))))}
export async function sendGroupRoomMessage(id:string,uid:string,text:string,replyTo?:string|null){const n=push(ref(db(),`groupMessages/${id}`));await set(n,{senderId:uid,text:text.slice(0,2000),replyTo:replyTo||null,createdAt:Date.now()});await update(ref(db(),`groupConversations/${id}`),{lastMessage:text.slice(0,120),lastMessageAt:Date.now()})}
export async function renameGroup(id:string,uid:string,name:string){const s=await get(ref(db(),`groupConversations/${id}`));if(!s.exists()||s.child('ownerId').val()!==uid)throw new Error('Only the group owner can rename this chat.');await update(ref(db(),`groupConversations/${id}`),{name:name.trim().slice(0,60)})}
export async function addGroupMember(id:string,uid:string,target:string){const s=await get(ref(db(),`groupConversations/${id}`));if(!s.exists()||s.child('ownerId').val()!==uid)throw new Error('Only the group owner can add members.');await set(ref(db(),`groupConversations/${id}/members/${target}`),true)}
export async function removeGroupMember(id:string,uid:string,target:string){const s=await get(ref(db(),`groupConversations/${id}`));if(!s.exists()||s.child('ownerId').val()!==uid)throw new Error('Only the group owner can remove members.');if(target===uid)throw new Error('Use Leave group to leave.');await remove(ref(db(),`groupConversations/${id}/members/${target}`))}
export async function leaveGroup(id:string,uid:string){const s=await get(ref(db(),`groupConversations/${id}`));if(!s.exists())return;if(s.child('ownerId').val()===uid){const members=Object.keys(s.child('members').val()||{}).filter(x=>x!==uid);if(members.length)await update(ref(db(),`groupConversations/${id}`),{ownerId:members[0]});else{await remove(ref(db(),`groupConversations/${id}`));await remove(ref(db(),`groupMessages/${id}`));return}}await remove(ref(db(),`groupConversations/${id}/members/${uid}`))}
export async function deleteGroupMessage(id:string,uid:string,messageId:string){const s=await get(ref(db(),`groupMessages/${id}/${messageId}`));if(!s.exists()||s.child('senderId').val()!==uid)throw new Error('You can only delete your own message.');await remove(ref(db(),`groupMessages/${id}/${messageId}`))}
export async function toggleGroupReaction(id:string,messageId:string,uid:string,emoji:string){const safe=emoji==='❤️'?'heart':emoji==='👍'?'like':'laugh',n=ref(db(),`groupMessageReactions/${id}/${messageId}/${safe}/${uid}`),s=await get(n);await set(n,s.exists()?null:true)}
export function subscribeGroupReactions(id:string,cb:(v:Record<string,Record<string,Record<string,boolean>>>)=>void){return onValue(ref(db(),`groupMessageReactions/${id}`),s=>cb(s.val()||{}))}
