import {DataSnapshot,equalTo,get,limitToLast,onValue,orderByChild,push,query,ref,runTransaction,serverTimestamp,set,update} from 'firebase/database';
import {auth,realtimeDb} from './client';
export type UserProfile={uid:string;username:string;displayName:string;bio?:string;avatarUrl?:string;createdAt?:number;role?:'user'|'admin';suspended?:boolean;accountVisibility?:'public'|'private'};
export type RealtimePost={id:string;authorId:string;authorName:string;username:string;text:string;media?:string[];createdAt:number;replyTo?:string|null;quotePostId?:string|null;counts:{likes:number;replies:number;reposts:number;views:number};isPrivate?:boolean;privacyOwnerId?:string|null};
export type Notification={id:string;actorId:string;actorName?:string;type:'like'|'reply'|'repost'|'follow'|'follow_request'|'mention'|'login';postId?:string;createdAt:number;read?:boolean};
export type Conversation={id:string;members:Record<string,boolean>;memberProfiles?:Record<string,{displayName:string;username:string}>;lastMessage?:string;lastMessageAt?:number};
export type ChatMessage={id:string;senderId:string;text:string;createdAt:number;seen?:boolean};
export type AiThread={id:string;title:string;createdAt:number;updatedAt:number};
export type AiMessage={id:string;role:'user'|'assistant';text:string;createdAt:number};
export type SupportTicket={id:string;subject:string;message:string;status:'open'|'in-progress'|'resolved';createdAt:number;updatedAt:number};
export type FollowResult={state:'following'|'unfollowed'|'requested'|'cancelled'};
type PostIndex={authorId:string;private:boolean;storageOwnerId:string;replyTo?:string|null};
const needDb=()=>{if(!realtimeDb)throw new Error('VAYROX live data is not configured');return realtimeDb};
const list=<T>(snap:DataSnapshot)=>Object.entries(snap.val()||{}).map(([id,value])=>({id,...value as T}));
const profileList=async(ids:string[])=>{const db=needDb(),snaps=await Promise.all(ids.map(id=>get(ref(db,`users/${id}`))));return snaps.flatMap(x=>x.exists()?[x.val() as UserProfile]:[])};
const toPost=(id:string,value:Omit<RealtimePost,'id'>,privatePost=false,privacyOwnerId?:string)=>({id,...value,isPrivate:privatePost,privacyOwnerId:privacyOwnerId||value.privacyOwnerId||null} as RealtimePost);
async function readPostIndex(postId:string){try{const s=await get(ref(needDb(),`postIndex/${postId}`));return s.exists()?s.val() as PostIndex:null}catch{return null}}
async function readPost(postId:string){const db=needDb();try{const publicSnap=await get(ref(db,`posts/${postId}`));if(publicSnap.exists())return toPost(postId,publicSnap.val(),false)}catch{}const index=await readPostIndex(postId);if(!index?.private)return null;try{const privateSnap=await get(ref(db,`privatePosts/${index.storageOwnerId}/${postId}`));return privateSnap.exists()?toPost(postId,privateSnap.val(),true,index.storageOwnerId):null}catch{return null}}
export async function upsertProfile(profile:UserProfile){const db=needDb(),handle=profile.username.trim().toLowerCase();if(!/^[a-z0-9_]{3,20}$/.test(handle))throw new Error('Username must be 3–20 letters, numbers, or underscores.');const claimed=await get(ref(db,`usernames/${handle}`));if(claimed.exists()&&claimed.val()!==profile.uid)throw new Error('That username is already taken.');const existing=await get(ref(db,`users/${profile.uid}`)),previous=existing.val() as UserProfile|null,next={...previous,...profile,username:handle,accountVisibility:profile.accountVisibility||previous?.accountVisibility||'public',createdAt:previous?.createdAt||Date.now()};const changes:Record<string,unknown>={[`users/${profile.uid}`]:next,[`usernames/${handle}`]:profile.uid};if(previous?.username&&previous.username.toLowerCase()!==handle)changes[`usernames/${previous.username.toLowerCase()}`]=null;await update(ref(db),changes)}
export function subscribeProfile(uid:string,cb:(value:UserProfile|null)=>void){return onValue(ref(needDb(),`users/${uid}`),s=>cb(s.exists()?s.val():null))}
export async function getProfileByUsername(username:string){const db=needDb(),id=await get(ref(db,`usernames/${username.toLowerCase()}`));if(!id.exists())return null;const profile=await get(ref(db,`users/${id.val()}`));return profile.exists()?profile.val() as UserProfile:null}
export function subscribeUsers(cb:(users:UserProfile[])=>void){return onValue(ref(needDb(),'users'),s=>cb((Object.values(s.val()||{}) as UserProfile[]).filter(Boolean)))}
export async function publishPost(post:Omit<RealtimePost,'id'|'createdAt'|'counts'|'isPrivate'|'privacyOwnerId'>){const db=needDb(),key=push(ref(db,'posts')).key!;let privatePost=false,storageOwnerId=post.authorId;if(post.replyTo){const parent=await readPostIndex(post.replyTo);if(parent?.private){privatePost=true;storageOwnerId=parent.storageOwnerId}}else{const profile=await get(ref(db,`users/${post.authorId}`));privatePost=(profile.val() as UserProfile|null)?.accountVisibility==='private'}const value={...post,text:post.text.slice(0,280),createdAt:serverTimestamp(),counts:{likes:0,replies:0,reposts:0,views:0},isPrivate:privatePost,privacyOwnerId:privatePost?storageOwnerId:null};const postPath=privatePost?`privatePosts/${storageOwnerId}/${key}`:`posts/${key}`;await set(ref(db,postPath),value);await set(ref(db,`postIndex/${key}`),{authorId:post.authorId,private:privatePost,storageOwnerId,replyTo:post.replyTo||null});if(post.replyTo){await set(ref(db,`replyIndex/${post.replyTo}/${key}`),{authorId:post.authorId,private:privatePost,storageOwnerId});await runTransaction(ref(db,`replyCounts/${post.replyTo}`),n=>(Number(n)||0)+1)}return key}
export function subscribeTimeline(cb:(posts:RealtimePost[])=>void,max=80){const db=needDb(),me=auth?.currentUser?.uid;let publicPosts:RealtimePost[]=[],privateGroups=new Map<string,RealtimePost[]>(),privateUnsubs:(()=>void)[]=[];const emit=()=>cb([...publicPosts,...[...privateGroups.values()].flat()].sort((a,b)=>b.createdAt-a.createdAt).slice(0,max));const publicQ=query(ref(db,'posts'),orderByChild('createdAt'),limitToLast(max));const publicUnsub=onValue(publicQ,s=>{publicPosts=list<Omit<RealtimePost,'id'>>(s).map(p=>({...p,isPrivate:false} as RealtimePost));emit()});if(!me)return publicUnsub;const mountPrivate=(ids:string[])=>{privateUnsubs.forEach(fn=>fn());privateUnsubs=[];privateGroups=new Map();for(const uid of [...new Set([me,...ids])]){const q=query(ref(db,`privatePosts/${uid}`),orderByChild('createdAt'),limitToLast(max));privateUnsubs.push(onValue(q,s=>{privateGroups.set(uid,list<Omit<RealtimePost,'id'>>(s).map(p=>({...p,isPrivate:true,privacyOwnerId:uid} as RealtimePost)));emit()},()=>{privateGroups.delete(uid);emit()}))}};const followUnsub=onValue(ref(db,`following/${me}`),s=>mountPrivate(Object.keys(s.val()||{})));return()=>{publicUnsub();followUnsub();privateUnsubs.forEach(fn=>fn())}}
export function subscribeUserPosts(uid:string,cb:(posts:RealtimePost[])=>void){const db=needDb(),viewer=auth?.currentUser?.uid;let publicPosts:RealtimePost[]=[],privatePosts:RealtimePost[]=[],privateUnsub:(()=>void)|null=null;const emit=()=>cb([...publicPosts,...privatePosts].sort((a,b)=>b.createdAt-a.createdAt));const publicQ=query(ref(db,'posts'),orderByChild('authorId'),equalTo(uid));const publicUnsub=onValue(publicQ,s=>{publicPosts=list<Omit<RealtimePost,'id'>>(s).map(p=>({...p,isPrivate:false} as RealtimePost));emit()});if(!viewer)return publicUnsub;const accessRef=ref(db,`followers/${uid}/${viewer}`);const accessUnsub=onValue(accessRef,s=>{const allowed=viewer===uid||s.exists();if(privateUnsub){privateUnsub();privateUnsub=null}privatePosts=[];if(allowed){privateUnsub=onValue(ref(db,`privatePosts/${uid}`),snap=>{privatePosts=list<Omit<RealtimePost,'id'>>(snap).filter(p=>p.authorId===uid).map(p=>({...p,isPrivate:true,privacyOwnerId:uid} as RealtimePost));emit()},()=>{privatePosts=[];emit()})}else emit()});return()=>{publicUnsub();accessUnsub();privateUnsub?.()}}
export function subscribePost(postId:string,cb:(post:RealtimePost|null)=>void){const db=needDb();let inner:(()=>void)|null=null;let stopped=false;void(async()=>{try{const publicSnap=await get(ref(db,`posts/${postId}`));if(stopped)return;if(publicSnap.exists()){inner=onValue(ref(db,`posts/${postId}`),s=>cb(s.exists()?toPost(postId,s.val(),false):null));return}const index=await readPostIndex(postId);if(stopped||!index?.private){cb(null);return}inner=onValue(ref(db,`privatePosts/${index.storageOwnerId}/${postId}`),s=>cb(s.exists()?toPost(postId,s.val(),true,index.storageOwnerId):null),()=>cb(null))}catch{cb(null)}})();return()=>{stopped=true;inner?.()}}
export function subscribeReplies(postId:string,cb:(posts:RealtimePost[])=>void){const db=needDb();let generation=0;return onValue(ref(db,`replyIndex/${postId}`),async s=>{const current=++generation,ids=Object.keys(s.val()||{}),items=await Promise.all(ids.map(readPost));if(current===generation)cb(items.filter(Boolean).sort((a,b)=>a!.createdAt-b!.createdAt) as RealtimePost[])},()=>cb([]))}
export function subscribeReplyCounts(cb:(counts:Record<string,number>)=>void){return onValue(ref(needDb(),'replyCounts'),s=>cb((s.val()||{}) as Record<string,number>))}
export async function toggleReaction(uid:string,postId:string,type:'likes'|'reposts'|'bookmarks'){const db=needDb(),node=ref(db,`${type}/${postId}/${uid}`),current=await get(node),active=!current.exists();await update(ref(db),{[`${type}/${postId}/${uid}`]:active||null,[`${type}ByUser/${uid}/${postId}`]:active||null});return active}
export function subscribeUserReactions(uid:string,type:'likes'|'reposts'|'bookmarks',cb:(ids:Set<string>)=>void){return onValue(ref(needDb(),`${type}ByUser/${uid}`),s=>cb(new Set(Object.keys(s.val()||{}))))}
export function subscribeReactionCounts(type:'likes'|'reposts',cb:(counts:Record<string,number>)=>void){return onValue(ref(needDb(),type),s=>{const counts:Record<string,number>={};Object.entries(s.val()||{}).forEach(([postId,users])=>counts[postId]=Object.keys((users as Record<string,boolean>)||{}).length);cb(counts)})}
export function subscribeBookmarkedPosts(uid:string,cb:(posts:RealtimePost[])=>void){return subscribeIndexedPosts(`bookmarksByUser/${uid}`,cb)}
export function subscribeRepostedPosts(uid:string,cb:(posts:RealtimePost[])=>void){return subscribeIndexedPosts(`repostsByUser/${uid}`,cb)}
export function subscribeLikedPosts(uid:string,cb:(posts:RealtimePost[])=>void){return subscribeIndexedPosts(`likesByUser/${uid}`,cb)}
function subscribeIndexedPosts(path:string,cb:(posts:RealtimePost[])=>void){let generation=0;return onValue(ref(needDb(),path),async s=>{const current=++generation,ids=Object.keys(s.val()||{}),items=await Promise.all(ids.map(readPost));if(current===generation)cb(items.filter(Boolean).sort((a,b)=>b!.createdAt-a!.createdAt) as RealtimePost[])})}
export async function deletePost(uid:string,postId:string){const db=needDb(),index=await readPostIndex(postId);if(!index)throw new Error('Post not found');if(index.authorId!==uid)throw new Error('You can only delete your own posts');const reactionUsers:{path:string;users:string[]}[]=[];for(const type of ['likes','reposts','bookmarks'] as const){const s=await get(ref(db,`${type}/${postId}`));reactionUsers.push({path:type,users:Object.keys(s.val()||{})})}const cleanup:Record<string,unknown>={};for(const group of reactionUsers){cleanup[`${group.path}/${postId}`]=null;for(const userId of group.users)cleanup[`${group.path}ByUser/${userId}/${postId}`]=null}await update(ref(db),cleanup);const postPath=index.private?`privatePosts/${index.storageOwnerId}/${postId}`:`posts/${postId}`;await set(ref(db,postPath),null);await set(ref(db,`postIndex/${postId}`),null);if(index.replyTo){await set(ref(db,`replyIndex/${index.replyTo}/${postId}`),null);await runTransaction(ref(db,`replyCounts/${index.replyTo}`),n=>Math.max(0,(Number(n)||0)-1))}}
export async function followUser(uid:string,target:string):Promise<FollowResult>{if(uid===target)return{state:'following'};const db=needDb(),followingNode=ref(db,`following/${uid}/${target}`),requestPath=`followRequests/${target}/${uid}`,current=await get(followingNode);if(current.exists()){await update(ref(db),{[`following/${uid}/${target}`]:null,[`followers/${target}/${uid}`]:null,[requestPath]:null});return{state:'unfollowed'}}const targetSnap=await get(ref(db,`users/${target}`)),targetProfile=targetSnap.val() as UserProfile|null;if(targetProfile?.accountVisibility==='private'){const requestNode=ref(db,requestPath),pending=await get(requestNode);if(pending.exists()){await set(requestNode,null);return{state:'cancelled'}}await set(requestNode,{createdAt:serverTimestamp()});return{state:'requested'}}await update(ref(db),{[`following/${uid}/${target}`]:true,[`followers/${target}/${uid}`]:true,[requestPath]:null});return{state:'following'}}
export function subscribeFollowing(uid:string,cb:(ids:Set<string>)=>void){return onValue(ref(needDb(),`following/${uid}`),s=>cb(new Set(Object.keys(s.val()||{}))))}
export function subscribeFollowers(uid:string,cb:(ids:Set<string>)=>void){return onValue(ref(needDb(),`followers/${uid}`),s=>cb(new Set(Object.keys(s.val()||{}))))}
export function subscribeFollowingProfiles(uid:string,cb:(items:UserProfile[])=>void){return subscribeProfilesIndex(`following/${uid}`,cb)}
export function subscribeFollowerProfiles(uid:string,cb:(items:UserProfile[])=>void){return subscribeProfilesIndex(`followers/${uid}`,cb)}
function subscribeProfilesIndex(path:string,cb:(items:UserProfile[])=>void){return onValue(ref(needDb(),path),async s=>cb(await profileList(Object.keys(s.val()||{}))))}
export function subscribeFollowRequest(targetUid:string,requesterUid:string,cb:(pending:boolean)=>void){return onValue(ref(needDb(),`followRequests/${targetUid}/${requesterUid}`),s=>cb(s.exists()))}
export function subscribeFollowRequests(targetUid:string,cb:(items:UserProfile[])=>void){return onValue(ref(needDb(),`followRequests/${targetUid}`),async s=>cb(await profileList(Object.keys(s.val()||{}))))}
export async function approveFollowRequest(targetUid:string,requesterUid:string){await update(ref(needDb()),{[`following/${requesterUid}/${targetUid}`]:true,[`followers/${targetUid}/${requesterUid}`]:true,[`followRequests/${targetUid}/${requesterUid}`]:null})}
export async function rejectFollowRequest(targetUid:string,requesterUid:string){await set(ref(needDb(),`followRequests/${targetUid}/${requesterUid}`),null)}
export async function createNotification(targetUid:string,payload:Omit<Notification,'id'|'createdAt'>){await push(ref(needDb(),`notifications/${targetUid}`),{...payload,createdAt:serverTimestamp(),read:false})}
export function subscribeNotifications(uid:string,cb:(items:Notification[])=>void){const q=query(ref(needDb(),`notifications/${uid}`),orderByChild('createdAt'),limitToLast(80));return onValue(q,s=>cb(list<Omit<Notification,'id'>>(s).reverse() as Notification[]))}
export async function markNotificationsRead(uid:string){const db=needDb(),snap=await get(ref(db,`notifications/${uid}`)),changes:Record<string,boolean>={};Object.entries(snap.val()||{}).forEach(([id,n])=>{if(!(n as Notification).read)changes[`notifications/${uid}/${id}/read`]=true});if(Object.keys(changes).length)await update(ref(db),changes)}
export async function ensureConversation(me:UserProfile,other:UserProfile){const db=needDb(),id=[me.uid,other.uid].sort().join('_'),members={[me.uid]:true,[other.uid]:true},memberProfiles={[me.uid]:{displayName:me.displayName,username:me.username},[other.uid]:{displayName:other.displayName,username:other.username}};await update(ref(db,`conversations/${id}`),{members,memberProfiles});await update(ref(db),{[`conversationsByUser/${me.uid}/${id}`]:true,[`conversationsByUser/${other.uid}/${id}`]:true});return id}
export function subscribeConversations(uid:string,cb:(items:Conversation[])=>void){return onValue(ref(needDb(),`conversationsByUser/${uid}`),async s=>{const ids=Object.keys(s.val()||{}),db=needDb(),snaps=await Promise.all(ids.map(id=>get(ref(db,`conversations/${id}`))));cb(snaps.flatMap((x,i)=>x.exists()?[{id:ids[i],...x.val()}]:[]).sort((a,b)=>(b.lastMessageAt||0)-(a.lastMessageAt||0)) as Conversation[])})}
export function subscribeMessages(id:string,cb:(items:ChatMessage[])=>void){const q=query(ref(needDb(),`messages/${id}`),orderByChild('createdAt'),limitToLast(100));return onValue(q,s=>cb(list<Omit<ChatMessage,'id'>>(s).sort((a,b)=>a.createdAt-b.createdAt) as ChatMessage[]))}
export async function sendMessage(conversationId:string,uid:string,text:string){const db=needDb(),node=push(ref(db,`messages/${conversationId}`));await set(node,{senderId:uid,text:text.slice(0,2000),createdAt:serverTimestamp(),seen:false});await update(ref(db,`conversations/${conversationId}`),{lastMessage:text.slice(0,2000),lastMessageAt:serverTimestamp()})}
export async function createAiThread(uid:string,title:string){const node=push(ref(needDb(),`aiThreads/${uid}`));await set(node,{title:title.slice(0,60),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return node.key!}
export function subscribeAiThreads(uid:string,cb:(items:AiThread[])=>void){const q=query(ref(needDb(),`aiThreads/${uid}`),orderByChild('updatedAt'),limitToLast(50));return onValue(q,s=>cb(list<Omit<AiThread,'id'>>(s).reverse() as AiThread[]))}
export function subscribeAiMessages(uid:string,threadId:string,cb:(items:AiMessage[])=>void){const q=query(ref(needDb(),`aiMessages/${uid}/${threadId}`),orderByChild('createdAt'),limitToLast(100));return onValue(q,s=>cb(list<Omit<AiMessage,'id'>>(s).sort((a,b)=>a.createdAt-b.createdAt) as AiMessage[]))}
export async function sendAiMessage(uid:string,threadId:string,role:'user'|'assistant',text:string){const db=needDb();await push(ref(db,`aiMessages/${uid}/${threadId}`),{role,text:text.slice(0,8000),createdAt:serverTimestamp()});await update(ref(db,`aiThreads/${uid}/${threadId}`),{updatedAt:serverTimestamp()})}
export async function deleteAiThread(uid:string,threadId:string){await update(ref(needDb()),{[`aiThreads/${uid}/${threadId}`]:null,[`aiMessages/${uid}/${threadId}`]:null})}
export async function createSupportTicket(uid:string,subject:string,message:string){const node=push(ref(needDb(),`supportTickets/${uid}`));await set(node,{subject:subject.slice(0,120),message:message.slice(0,4000),status:'open',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return node.key}
export function subscribeSupportTickets(uid:string,cb:(items:SupportTicket[])=>void){const q=query(ref(needDb(),`supportTickets/${uid}`),orderByChild('updatedAt'),limitToLast(30));return onValue(q,s=>cb(list<Omit<SupportTicket,'id'>>(s).reverse() as SupportTicket[]))}
export async function adminDeletePost(postId:string){const db=needDb(),index=await readPostIndex(postId);if(index){await set(ref(db,index.private?`privatePosts/${index.storageOwnerId}/${postId}`:`posts/${postId}`),null);await set(ref(db,`postIndex/${postId}`),null);return}await set(ref(db,`posts/${postId}`),null)}
export async function adminSetSuspended(uid:string,suspended:boolean){await update(ref(needDb(),`users/${uid}`),{suspended})}
