import { DataSnapshot,equalTo,get,limitToLast,onValue,orderByChild,push,query,ref,runTransaction,serverTimestamp,set,update } from 'firebase/database';
import { realtimeDb } from './client';
export type UserProfile={uid:string;username:string;displayName:string;bio?:string;avatarUrl?:string;createdAt?:number;role?:'user'|'admin';suspended?:boolean};
export type RealtimePost={id:string;authorId:string;authorName:string;username:string;text:string;media?:string[];createdAt:number;replyTo?:string|null;quotePostId?:string|null;counts:{likes:number;replies:number;reposts:number;views:number}};
export type Notification={id:string;actorId:string;actorName?:string;type:'like'|'reply'|'repost'|'follow'|'mention';postId?:string;createdAt:number;read?:boolean};
export type Conversation={id:string;members:Record<string,boolean>;memberProfiles?:Record<string,{displayName:string;username:string}>;lastMessage?:string;lastMessageAt?:number};
export type ChatMessage={id:string;senderId:string;text:string;createdAt:number;seen?:boolean};
const needDb=()=>{if(!realtimeDb)throw new Error('Firebase Realtime Database is not configured');return realtimeDb};
const list=<T>(snap:DataSnapshot)=>Object.entries(snap.val()||{}).map(([id,value])=>({id,...value as T}));
export async function upsertProfile(profile:UserProfile){const db=needDb(),existing=await get(ref(db,`users/${profile.uid}`)),previous=existing.val() as UserProfile|null,next={...previous,...profile,createdAt:previous?.createdAt||Date.now()};const changes:Record<string,unknown>={[`users/${profile.uid}`]:next,[`usernames/${profile.username.toLowerCase()}`]:profile.uid};if(previous?.username&&previous.username!==profile.username)changes[`usernames/${previous.username.toLowerCase()}`]=null;await update(ref(db),changes)}
export function subscribeProfile(uid:string,cb:(value:UserProfile|null)=>void){return onValue(ref(needDb(),`users/${uid}`),s=>cb(s.exists()?s.val():null))}
export async function getProfileByUsername(username:string){const db=needDb(),id=await get(ref(db,`usernames/${username.toLowerCase()}`));if(!id.exists())return null;const profile=await get(ref(db,`users/${id.val()}`));return profile.exists()?profile.val() as UserProfile:null}
export function subscribeUsers(cb:(users:UserProfile[])=>void){return onValue(ref(needDb(),'users'),s=>cb(Object.values(s.val()||{})))}
export async function publishPost(post:Omit<RealtimePost,'id'|'createdAt'|'counts'>){const db=needDb(),node=push(ref(db,'posts'));await set(node,{...post,createdAt:serverTimestamp(),counts:{likes:0,replies:0,reposts:0,views:0}});if(post.replyTo)await runTransaction(ref(db,`posts/${post.replyTo}/counts/replies`),n=>(n||0)+1);return node.key}
export function subscribeTimeline(cb:(posts:RealtimePost[])=>void,max=50){const q=query(ref(needDb(),'posts'),orderByChild('createdAt'),limitToLast(max));return onValue(q,s=>cb(list<Omit<RealtimePost,'id'>>(s).reverse() as RealtimePost[]))}
export function subscribeUserPosts(uid:string,cb:(posts:RealtimePost[])=>void){const q=query(ref(needDb(),'posts'),orderByChild('authorId'),equalTo(uid));return onValue(q,s=>cb(list<Omit<RealtimePost,'id'>>(s).sort((a,b)=>b.createdAt-a.createdAt) as RealtimePost[]))}
export function subscribePost(postId:string,cb:(post:RealtimePost|null)=>void){return onValue(ref(needDb(),`posts/${postId}`),s=>cb(s.exists()?{id:postId,...s.val()}:null))}
export function subscribeReplies(postId:string,cb:(posts:RealtimePost[])=>void){const q=query(ref(needDb(),'posts'),orderByChild('replyTo'),equalTo(postId));return onValue(q,s=>cb(list<Omit<RealtimePost,'id'>>(s).sort((a,b)=>a.createdAt-b.createdAt) as RealtimePost[]))}
export async function toggleReaction(uid:string,postId:string,type:'likes'|'reposts'|'bookmarks'){const db=needDb(),node=ref(db,`${type}/${postId}/${uid}`),current=await get(node),active=!current.exists();await update(ref(db),{[`${type}/${postId}/${uid}`]:active||null,[`${type}ByUser/${uid}/${postId}`]:active||null});if(type!=='bookmarks')await runTransaction(ref(db,`posts/${postId}/counts/${type}`),n=>Math.max(0,(n||0)+(active?1:-1)));return active}
export function subscribeUserReactions(uid:string,type:'likes'|'reposts'|'bookmarks',cb:(ids:Set<string>)=>void){return onValue(ref(needDb(),`${type}ByUser/${uid}`),s=>cb(new Set(Object.keys(s.val()||{}))))}
export function subscribeBookmarkedPosts(uid:string,cb:(posts:RealtimePost[])=>void){return onValue(ref(needDb(),`bookmarksByUser/${uid}`),async s=>{const ids=Object.keys(s.val()||{}),snaps=await Promise.all(ids.map(id=>get(ref(needDb(),`posts/${id}`))));cb(snaps.flatMap((x,i)=>x.exists()?[{id:ids[i],...x.val()}]:[]).sort((a,b)=>b.createdAt-a.createdAt))})}
export async function followUser(uid:string,target:string){const db=needDb(),node=ref(db,`following/${uid}/${target}`),current=await get(node),active=!current.exists();await update(ref(db),{[`following/${uid}/${target}`]:active||null,[`followers/${target}/${uid}`]:active||null});return active}
export function subscribeFollowing(uid:string,cb:(ids:Set<string>)=>void){return onValue(ref(needDb(),`following/${uid}`),s=>cb(new Set(Object.keys(s.val()||{}))))}
export async function createNotification(targetUid:string,payload:Omit<Notification,'id'|'createdAt'>){await push(ref(needDb(),`notifications/${targetUid}`),{...payload,createdAt:serverTimestamp(),read:false})}
export function subscribeNotifications(uid:string,cb:(items:Notification[])=>void){const q=query(ref(needDb(),`notifications/${uid}`),orderByChild('createdAt'),limitToLast(60));return onValue(q,s=>cb(list<Omit<Notification,'id'>>(s).reverse() as Notification[]))}
export async function ensureConversation(me:UserProfile,other:UserProfile){const id=[me.uid,other.uid].sort().join('_'),data={members:{[me.uid]:true,[other.uid]:true},memberProfiles:{[me.uid]:{displayName:me.displayName,username:me.username},[other.uid]:{displayName:other.displayName,username:other.username}}};await update(ref(needDb()),{[`conversations/${id}/members`]:data.members,[`conversations/${id}/memberProfiles`]:data.memberProfiles,[`conversationsByUser/${me.uid}/${id}`]:true,[`conversationsByUser/${other.uid}/${id}`]:true});return id}
export function subscribeConversations(uid:string,cb:(items:Conversation[])=>void){return onValue(ref(needDb(),`conversationsByUser/${uid}`),async s=>{const ids=Object.keys(s.val()||{}),snaps=await Promise.all(ids.map(id=>get(ref(needDb(),`conversations/${id}`))));cb(snaps.flatMap((x,i)=>x.exists()?[{id:ids[i],...x.val()}]:[]).sort((a,b)=>(b.lastMessageAt||0)-(a.lastMessageAt||0)) as Conversation[])})}
export function subscribeMessages(id:string,cb:(items:ChatMessage[])=>void){const q=query(ref(needDb(),`messages/${id}`),orderByChild('createdAt'),limitToLast(100));return onValue(q,s=>cb(list<Omit<ChatMessage,'id'>>(s).sort((a,b)=>a.createdAt-b.createdAt) as ChatMessage[]))}
export async function sendMessage(conversationId:string,uid:string,text:string){const db=needDb(),node=push(ref(db,`messages/${conversationId}`));await set(node,{senderId:uid,text:text.slice(0,2000),createdAt:serverTimestamp(),seen:false});await update(ref(db,`conversations/${conversationId}`),{lastMessage:text.slice(0,2000),lastMessageAt:serverTimestamp()})}
export async function adminDeletePost(postId:string){await set(ref(needDb(),`posts/${postId}`),null)}
export async function adminSetSuspended(uid:string,suspended:boolean){await update(ref(needDb(),`users/${uid}`),{suspended})}
