import{get,onValue,push,ref,serverTimestamp,set,update}from'firebase/database';
import{realtimeDb}from'./client';
import type{UserProfile}from'./realtime';
export type DmPermission='everyone'|'following'|'nobody';
export type SafetySettings={dmPermission:DmPermission};
const needDb=()=>{if(!realtimeDb)throw new Error('VAYROX live data is not configured');return realtimeDb};
const conversationId=(a:string,b:string)=>[a,b].sort().join('_');
async function profiles(ids:string[]){const db=needDb(),snaps=await Promise.all(ids.map(id=>get(ref(db,`users/${id}`))));return snaps.flatMap(s=>s.exists()?[s.val() as UserProfile]:[])}
export function subscribeSafetyIds(uid:string,type:'blocks'|'mutes',cb:(ids:Set<string>)=>void){return onValue(ref(needDb(),`${type}/${uid}`),s=>cb(new Set(Object.keys(s.val()||{}))))}
export function subscribeSafetyProfiles(uid:string,type:'blocks'|'mutes',cb:(items:UserProfile[])=>void){return onValue(ref(needDb(),`${type}/${uid}`),async s=>cb(await profiles(Object.keys(s.val()||{}))))}
export function subscribeSafetySettings(uid:string,cb:(settings:SafetySettings)=>void){return onValue(ref(needDb(),`safetySettings/${uid}`),s=>cb({dmPermission:(s.child('dmPermission').val()||'everyone') as DmPermission}))}
export async function updateSafetySettings(uid:string,settings:SafetySettings){await set(ref(needDb(),`safetySettings/${uid}`),settings)}
export async function toggleMute(uid:string,targetUid:string){if(uid===targetUid)throw new Error('You cannot mute yourself');const db=needDb(),node=ref(db,`mutes/${uid}/${targetUid}`),current=await get(node),active=!current.exists();await set(node,active||null);return active}
export async function toggleBlock(uid:string,targetUid:string){if(uid===targetUid)throw new Error('You cannot block yourself');const db=needDb(),node=ref(db,`blocks/${uid}/${targetUid}`),current=await get(node),active=!current.exists(),chatId=conversationId(uid,targetUid),chat=await get(ref(db,`conversations/${chatId}`)),hasChat=chat.exists()&&chat.child('members').child(uid).val()===true;const changes:Record<string,unknown>={};if(!active){changes[`blocks/${uid}/${targetUid}`]=null;if(hasChat)changes[`conversationBlocks/${chatId}/${uid}`]=null;await update(ref(db),changes);return false}Object.assign(changes,{[`blocks/${uid}/${targetUid}`]:true,[`mutes/${uid}/${targetUid}`]:true,[`following/${uid}/${targetUid}`]:null,[`followers/${targetUid}/${uid}`]:null,[`following/${targetUid}/${uid}`]:null,[`followers/${uid}/${targetUid}`]:null,[`followRequests/${uid}/${targetUid}`]:null,[`followRequests/${targetUid}/${uid}`]:null});if(hasChat)changes[`conversationBlocks/${chatId}/${uid}`]=true;await update(ref(db),changes);return true}
export async function isBlockedEitherWay(uid:string,targetUid:string){const db=needDb(),[mine,theirs]=await Promise.all([get(ref(db,`blocks/${uid}/${targetUid}`)),get(ref(db,`blocks/${targetUid}/${uid}`))]);return mine.exists()||theirs.exists()}
export async function canStartMessage(uid:string,targetUid:string){if(await isBlockedEitherWay(uid,targetUid))return{allowed:false,reason:'Messaging is unavailable because one of these accounts has blocked the other.'};const db=needDb(),setting=await get(ref(db,`safetySettings/${targetUid}/dmPermission`)),permission=(setting.val()||'everyone') as DmPermission;if(permission==='nobody')return{allowed:false,reason:'This account is not accepting new messages.'};if(permission==='following'){const follows=await get(ref(db,`followers/${targetUid}/${uid}`));if(!follows.exists())return{allowed:false,reason:'This account only accepts messages from followers.'}}return{allowed:true,reason:''}}
export async function ensureSafeConversation(me:UserProfile,other:UserProfile){const check=await canStartMessage(me.uid,other.uid);if(!check.allowed)throw new Error(check.reason);const db=needDb(),id=conversationId(me.uid,other.uid),existing=await get(ref(db,`conversations/${id}`));if(!existing.exists()){await set(ref(db,`conversations/${id}`),{initiatorId:me.uid,recipientId:other.uid,members:{[me.uid]:true,[other.uid]:true},memberProfiles:{[me.uid]:{displayName:me.displayName,username:me.username},[other.uid]:{displayName:other.displayName,username:other.username}}})}else{await update(ref(db,`conversations/${id}`),{[`memberProfiles/${me.uid}`]:{displayName:me.displayName,username:me.username},[`memberProfiles/${other.uid}`]:{displayName:other.displayName,username:other.username}})}await update(ref(db),{[`conversationsByUser/${me.uid}/${id}`]:true,[`conversationsByUser/${other.uid}/${id}`]:true});return id}
export async function reportPost(reporterId:string,postId:string,targetUid:string,reason:string){const node=push(ref(needDb(),'reports'));await set(node,{reporterId,targetUid,postId,type:'post',reason:reason.slice(0,160),status:'open',createdAt:serverTimestamp()});return node.key}
export async function reportAccount(reporterId:string,targetUid:string,reason:string){const node=push(ref(needDb(),'reports'));await set(node,{reporterId,targetUid,type:'account',reason:reason.slice(0,160),status:'open',createdAt:serverTimestamp()});return node.key}
