'use client';
import { useState } from 'react';
import { AnimatePresence,motion } from 'framer-motion';
import { Bell,Bookmark,Compass,Ellipsis,Feather,Heart,Home,Image,Mail,MessageCircle,MoreHorizontal,Repeat2,Search,Share,Smile,Sparkles,UserRound,Video,X } from 'lucide-react';
import Link from 'next/link';
type Post={id:string;name:string;handle:string;time:string;text:string;avatar:string;image?:string;replies:number;reposts:number;likes:number;views:string;liked?:boolean;reposted?:boolean};
const seed:Post[]=[
 {id:'p1',name:'Maya Chen',handle:'mayamakes',time:'2m',avatar:'MC',text:'Small teams can build astonishing things when the feedback loop is this fast. We shipped the new canvas today ✦',replies:28,reposts:73,likes:618,views:'18K',image:'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1000&q=80'},
 {id:'p2',name:'Noah Williams',handle:'noahw',time:'18m',avatar:'NW',text:'The best products feel obvious in retrospect. The work is making them feel inevitable beforehand.',replies:14,reposts:41,likes:392,views:'9.4K'},
 {id:'p3',name:'Lena Ortiz',handle:'lena.codes',time:'1h',avatar:'LO',text:'Just open-sourced a tiny animation toolkit for delightful interface transitions. Zero config, sensible defaults, and spring physics.',replies:36,reposts:129,likes:1100,views:'31K'}];
const nav=[['/home','Home',Home],['/explore','Explore',Compass],['/notifications','Notifications',Bell],['/messages','Messages',Mail],['/i/bookmarks','Bookmarks',Bookmark],['/averystone','Profile',UserRound]] as const;
export function SocialApp(){
 const[posts,setPosts]=useState(seed),[text,setText]=useState(''),[tab,setTab]=useState('foryou'),[notice,setNotice]=useState(''),[compose,setCompose]=useState(false);const count=280-text.length;
 const submit=()=>{const body=text.trim();if(!body||count<0)return;setPosts(p=>[{id:crypto.randomUUID(),name:'Avery Stone',handle:'averystone',time:'now',avatar:'AS',text:body,replies:0,reposts:0,likes:0,views:'0'},...p]);setText('');setCompose(false);setNotice('Post published');setTimeout(()=>setNotice(''),2200)};
 const toggle=(id:string,key:'liked'|'reposted')=>setPosts(p=>p.map(x=>x.id===id?{...x,[key]:!x[key],[key==='liked'?'likes':'reposts']:x[key==='liked'?'likes':'reposts']+(x[key]?-1:1)}:x));
 return <div className="min-h-screen bg-background"><div className="mx-auto grid min-h-screen max-w-[1260px] grid-cols-1 md:grid-cols-[88px_minmax(0,640px)] lg:grid-cols-[240px_minmax(0,640px)_330px]">
  <aside className="fixed bottom-0 z-40 flex w-full items-center justify-around border-t bg-background/95 px-2 py-2 backdrop-blur-xl md:sticky md:top-0 md:h-screen md:w-auto md:flex-col md:items-stretch md:justify-start md:border-r md:border-t-0 md:px-3 md:py-4 lg:px-5"><Link href="/home" aria-label="eX home" className="mb-5 hidden items-center gap-2 px-3 md:flex"><Logo/><span className="hidden text-xl font-bold lg:block">eX</span></Link><nav className="flex w-full items-center justify-around md:flex-col md:items-stretch md:gap-1">{nav.map(([href,label,Icon],i)=><Link key={href} href={href} aria-label={label} className={`relative flex items-center gap-4 rounded-2xl p-3 text-[16px] font-medium transition hover:bg-secondary ${i===0?'text-primary':''}`}><Icon className="size-[23px]" strokeWidth={i===0?2.5:1.8}/><span className="hidden lg:block">{label}</span>{label==='Notifications'&&<i className="absolute left-7 top-2 h-2 w-2 rounded-full bg-[#ff5c7c]"/>}</Link>)}</nav><button onClick={()=>setCompose(true)} className="mt-5 hidden h-12 items-center justify-center gap-2 rounded-full bg-primary font-semibold text-white shadow-lg shadow-primary/20 transition hover:-translate-y-0.5 md:flex"><Feather className="size-5"/><span className="hidden lg:inline">Post</span></button><button className="mt-auto hidden items-center gap-3 rounded-2xl p-3 text-left hover:bg-secondary md:flex"><Avatar initials="AS"/><span className="hidden lg:block"><b className="block text-sm">Avery Stone</b><small className="text-muted-foreground">@averystone</small></span><MoreHorizontal className="ml-auto hidden size-4 lg:block"/></button></aside>
  <main className="min-h-screen border-r"><header className="sticky top-0 z-30 border-b bg-background/85 backdrop-blur-xl"><div className="flex h-14 items-center px-4"><div className="md:hidden"><Logo/></div><h1 className="ml-3 text-lg font-bold md:ml-0">Home</h1><button className="ml-auto rounded-full p-2 hover:bg-secondary" aria-label="Timeline settings"><Sparkles className="size-5"/></button></div><div className="grid grid-cols-2"><button onClick={()=>setTab('foryou')} className="relative h-12 text-sm font-semibold">For you{tab==='foryou'&&<motion.span layoutId="tab" className="absolute inset-x-9 bottom-0 h-[3px] rounded-full bg-primary"/>}</button><button onClick={()=>setTab('following')} className="relative h-12 text-sm font-semibold text-muted-foreground">Following{tab==='following'&&<motion.span layoutId="tab" className="absolute inset-x-9 bottom-0 h-[3px] rounded-full bg-primary"/>}</button></div></header><Composer text={text} setText={setText} count={count} submit={submit}/><AnimatePresence initial={false}>{posts.map(post=><PostCard key={post.id} post={post} toggle={toggle}/>)}</AnimatePresence><div className="pb-24 pt-8 text-center text-sm text-muted-foreground">You’re all caught up ✦</div></main>
  <aside className="hidden px-6 lg:block"><div className="sticky top-0 space-y-5 py-3"><label className="flex h-11 items-center gap-3 rounded-full bg-secondary px-4 text-muted-foreground focus-within:ring-2 focus-within:ring-primary"><Search className="size-5"/><input className="w-full bg-transparent text-sm text-foreground outline-none" placeholder="Search eX" aria-label="Search eX"/></label><Rail title="What’s happening"><Trend group="Design · Trending" title="Tiny interfaces" posts="12.8K posts"/><Trend group="Technology · Trending" title="Local-first software" posts="8,406 posts"/><Trend group="Trending in Pakistan" title="Indie hackers" posts="5,210 posts"/><button className="px-4 pb-4 text-sm font-medium text-primary">Show more</button></Rail><Rail title="Who to follow"><Follow name="Priya Shah" handle="priyashah" initials="PS"/><Follow name="Omar Farooq" handle="omarf" initials="OF"/></Rail><p className="px-3 text-xs leading-5 text-muted-foreground">Terms · Privacy · Cookies · Accessibility · © 2026 eX</p></div></aside>
 </div><AnimatePresence>{compose&&<Modal onClose={()=>setCompose(false)}><Composer text={text} setText={setText} count={count} submit={submit} modal/></Modal>}</AnimatePresence><AnimatePresence>{notice&&<motion.div initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} exit={{y:20,opacity:0}} role="status" className="fixed bottom-20 left-1/2 z-50 -translate-x-1/2 rounded-full bg-foreground px-5 py-3 text-sm font-semibold text-background shadow-xl md:bottom-6">{notice}</motion.div>}</AnimatePresence></div>}
function Logo(){return <span className="grid size-10 place-items-center rounded-[14px] bg-gradient-to-br from-[#3458ef] via-[#607cf7] to-[#ff617c] text-lg font-black italic text-white shadow-md shadow-blue-500/20">eX</span>}
function Avatar({initials}:{initials:string}){return <span className="grid size-10 shrink-0 place-items-center rounded-full bg-gradient-to-br from-[#dfe5ff] to-[#ffe2e8] text-xs font-bold text-[#2c4092] ring-1 ring-black/5 dark:from-[#273153] dark:to-[#4c2835] dark:text-white">{initials}</span>}
function Composer({text,setText,count,submit,modal=false}:{text:string;setText:(v:string)=>void;count:number;submit:()=>void;modal?:boolean}){return <section className={`${modal?'border-0 p-1':'border-b p-4'} flex gap-3`}><Avatar initials="AS"/><div className="min-w-0 flex-1"><textarea value={text} onChange={e=>setText(e.target.value)} autoFocus={modal} rows={modal?5:2} placeholder="What’s happening?" className="w-full resize-none bg-transparent pt-2 text-[18px] leading-6 outline-none placeholder:text-muted-foreground/80"/><div className="mt-3 flex items-center border-t pt-3 text-primary"><button aria-label="Add image" className="rounded-full p-2 hover:bg-accent"><Image className="size-5"/></button><button aria-label="Add video" className="rounded-full p-2 hover:bg-accent"><Video className="size-5"/></button><button aria-label="Add emoji" className="rounded-full p-2 hover:bg-accent"><Smile className="size-5"/></button><span className={`ml-auto mr-3 text-xs ${count<0?'text-red-500':'text-muted-foreground'}`}>{text?count:''}</span><button onClick={submit} disabled={!text.trim()||count<0} className="rounded-full bg-primary px-5 py-2 text-sm font-bold text-white disabled:opacity-45">Post</button></div></div></section>}
function PostCard({post,toggle}:{post:Post;toggle:(id:string,key:'liked'|'reposted')=>void}){return <motion.article layout initial={{opacity:0,y:-14}} animate={{opacity:1,y:0}} className="flex gap-3 border-b px-4 py-4 transition hover:bg-muted/55"><Avatar initials={post.avatar}/><div className="min-w-0 flex-1"><div className="flex items-center gap-1 text-sm"><b className="truncate">{post.name}</b><span className="truncate text-muted-foreground">@{post.handle} · {post.time}</span><button className="ml-auto rounded-full p-1 text-muted-foreground hover:bg-accent"><Ellipsis className="size-4"/></button></div><p className="mt-1 text-[15px] leading-[1.45]">{post.text}</p>{post.image&&<img src={post.image} alt="Colorful product design workspace" className="mt-3 max-h-[390px] w-full rounded-2xl border object-cover"/>}<div className="mt-3 flex max-w-[470px] items-center justify-between text-xs text-muted-foreground"><Action icon={MessageCircle} label={post.replies}/><Action active={post.reposted} onClick={()=>toggle(post.id,'reposted')} icon={Repeat2} label={post.reposts}/><Action active={post.liked} onClick={()=>toggle(post.id,'liked')} icon={Heart} label={post.likes} pink/><Action icon={Sparkles} label={post.views}/><Action icon={Share}/></div></div></motion.article>}
function Action({icon:Icon,label,onClick,active,pink}:{icon:any;label?:string|number;onClick?:()=>void;active?:boolean;pink?:boolean}){return <button onClick={onClick} className={`flex items-center gap-1 rounded-full transition hover:text-primary ${active?(pink?'text-[#f04464]':'text-emerald-500'):''}`}><span className="rounded-full p-2 hover:bg-accent"><Icon className="size-[18px]" fill={active&&pink?'currentColor':'none'}/></span>{label!==undefined&&<span>{typeof label==='number'&&label>999?(label/1000).toFixed(1)+'K':label}</span>}</button>}
function Rail({title,children}:{title:string;children:React.ReactNode}){return <section className="overflow-hidden rounded-2xl border bg-card"><h2 className="px-4 pb-2 pt-4 text-xl font-extrabold">{title}</h2>{children}</section>}
function Trend({group,title,posts}:{group:string;title:string;posts:string}){return <button className="block w-full px-4 py-3 text-left hover:bg-secondary"><span className="text-xs text-muted-foreground">{group}</span><b className="block text-sm">{title}</b><span className="text-xs text-muted-foreground">{posts}</span></button>}
function Follow({name,handle,initials}:{name:string;handle:string;initials:string}){const[on,setOn]=useState(false);return <div className="flex items-center gap-3 px-4 py-3"><Avatar initials={initials}/><span className="min-w-0 flex-1"><b className="block truncate text-sm">{name}</b><small className="text-muted-foreground">@{handle}</small></span><button onClick={()=>setOn(v=>!v)} className={`rounded-full px-4 py-2 text-xs font-bold ${on?'border':'bg-foreground text-background'}`}>{on?'Following':'Follow'}</button></div>}
function Modal({onClose,children}:{onClose:()=>void;children:React.ReactNode}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>e.target===e.currentTarget&&onClose()} className="fixed inset-0 z-50 flex items-start justify-center bg-black/45 p-3 pt-[10vh] backdrop-blur-sm"><motion.div initial={{scale:.96,y:-15}} animate={{scale:1,y:0}} className="w-full max-w-xl rounded-3xl bg-background p-4 shadow-2xl"><button onClick={onClose} className="mb-2 rounded-full p-2 hover:bg-secondary" aria-label="Close composer"><X className="size-5"/></button>{children}</motion.div></motion.div>}
